---
  hostname: ntdzbclvp01
  loopback0: 10.137.84.31
  local_bgp_asn: 64805
# define vrfs
  vrf_definition:
    vrf_azcd21:
      vrf_name: AZCD21
      vrf_dot1q: 675
    vrf_azcq21:
      vrf_name: AZCQ21
      vrf_dot1q: 676
    vrf_azcp21:
      vrf_name: AZCP21
      vrf_dot1q: 677
    vrf_azcd21-fvrf:
      vrf_name: AZCD21-FVRF
      vrf_dot1q: 1675
    vrf_azcq21-fvrf:
      vrf_name: AZCQ21-FVRF
      vrf_dot1q: 1676
    vrf_azcp21-fvrf:
      vrf_name: AZCP21-FVRF
      vrf_dot1q: 1677
#  define l3 interface 
  l3_interfaces:
    Te0/0/11:
      description: "connection to ndcnbclvp01 Te0/0/11"
      lacp: absent
    Te0/0/10:
      description: "connection to nacnbclvp01 Te0/0/10"
      lacp: absent
# define loopback interface 
  loopback_interfaces:
    loop675:
      loop_vrf: AZCD21
      loop_ipv4: 10.137.84.14
      loop_description: "vrf azcp21 loopback interface"
    loop676:
      loop_vrf: AZCQ21
      loop_ipv4: 10.137.84.15
      loop_description: "vrf azcp21 loopback interface"
    loop677:
      loop_vrf: AZCP21
      loop_ipv4: 10.137.84.13
      loop_description: "vrf azcp21 loopback interface"
  layer3_sub_int:
    Te0/0/11.675:
      dot1q: 675
      ipv4_add: 10.137.80.210
      vrf : AZCD21-FVRF
      description: "connection to ndcnbclvp01 Te0/0/11.675"
    Te0/0/11.676:
      dot1q: 676
      ipv4_add: 10.137.80.226
      vrf : AZCQ21-FVRF
      description: "connection to ndnbclvp01 Te0/0/11.677"
    Te0/0/11.677:
      dot1q: 677
      ipv4_add: 10.137.80.2
      vrf : AZCP21-FVRF
      description: "connection to ndcnbclvp01 Te0/0/11.677"
    Te0/0/10.675:
      dot1q: 675
      ipv4_add: 10.137.64.218 
      vrf : AZCD21-FVRF
      description: "connection to nacnbclvp01 Te0/0/10.675"
    Te0/0/10.676:
      dot1q: 676
      ipv4_add: 10.137.64.234
      vrf : AZCQ21-FVRF
      description: "connection to nacnbclvp01 Te0/0/10.676"
    Te0/0/10.677:
      dot1q: 677
      ipv4_add: 10.136.64.202
      vrf : AZCP21-FVRF
      description: "connection to nacnbclvp01 Te0/0/10.677"
  vti_tunnel_interfaces:
    tunnel675:
      vrf: AZCD21
      ipv4: 10.137.80.94
      src: 10.137.80.210
      dest: 10.137.80.209
      desc: 
      fvrf: AZCD21-FVRF 
    tunnel676:
      vrf: AZCQ21
      ipv4: 10.137.80.158 
      src: 10.137.80.226
      dest: 10.137.80.225
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel677:
      vrf: AZCP21
      ipv4: 10.137.80.30 
      src: 10.137.80.2
      dest: 10.137.80.1  
      desc: 
      fvrf: AZCP21-FVRF
    tunnel1675:
      vrf: AZCD21
      ipv4: 10.137.64.102
      src: 10.137.64.218
      dest: 10.137.64.217
      desc: 
      fvrf: AZCD21-FVRF
    tunnel1676:
      vrf: AZCQ21
      ipv4: 10.137.64.166 
      src: 10.137.64.234
      dest: 10.137.64.233
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel1677:
      vrf: AZCP21
      ipv4: 10.137.64.38
      src: 10.137.64.202
      dest: 10.137.64.201
      desc: 
      fvrf: AZCP21-FVRF
  bgp_neighbors:
    da3colo_vp01peer1:
      remote_asn: 65206
      remote_ipv4: 10.137.80.93
      bgp_type: ebgp
      bgp_vrf: AZCD21
    da3colo_vp01peer2:
      remote_asn: 65206
      remote_ipv4: 10.137.80.157
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    da3colo_vp01peer3:
      remote_asn: 65206
      remote_ipv4: 10.137.80.29
      bgp_type: ebgp
      bgp_vrf: AZCP21
    dc11_vp01peer1:
      remote_asn: 65188
      remote_ipv4: 10.137.64.101
      bgp_type: ebgp
      bgp_vrf: AZCD21
    cd11_vp01peer2:
      remote_asn: 65188
      remote_ipv4: 10.137.64.165
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    dc11_vp01peer3:
      remote_asn: 65188
      remote_ipv4: 10.137.64.37
      bgp_type: ebgp
      bgp_vrf: AZCP21
  ikev2_policy:
    fvrf1: AZCD21-FVRF
    fvrf2: AZCQ21-FVRF
    fvrf3: AZCP21-FVRF
